
version: '3'
services:
  node:
    build: .
    ports:
      - "5000:5000"
    tty: true
    stdin_open: true
    volumes:
      - "./:/usr/src/app"
      - "reserved:/usr/src/app/node_modules"

volumes:
  reserved: